spring:
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/RescueTeamNysa
    platform: postgres
    password: lol112233
  jpa:
    hibernate:
      ddl-auto: update
      database-platform;: PostgreSQLDialect

    show-sql: true
